export const dummyProperties = [
  {
    id: "1",
    title: "Modern Luxury Apartment",
    location: "New York",
    price: 2500,
    type: "Apartment",
    status: "rent",
    bedrooms: 4,
    bathrooms: 3,
    area: 2200,
    features: true,
    image: "/images/image1.jpg",
    description:
      "A stunning luxury apartment with luxury interiors, spacious rooms, and a wide living area.",
  },
  {
    id: "2",
    title: "Cozy Family House",
    location: "Los Angeles",
    price: 420000,
    type: "House",
    status: "sale",
    bedrooms: 5,
    bathrooms: 4,
    area: 3500,
    features: true,
    image: "/images/image2.jpg",
    description:
      "Beautiful family home with a large backyard, modern kitchen, and premium finishes.",
  },
  {
    id: "3",
    title: "Downtown Studio Apartment",
    location: "Chicago",
    price: 1800,
    type: "Apartment",
    status: "rent",
    bedrooms: 1,
    bathrooms: 1,
    area: 900,
    features: false,
    image: "/images/image3.jpg",
    description:
      "Compact and stylish studio apartment located in the heart of downtown.",
  },
  {
    id: "4",
    title: "Beachfront Villa",
    location: "Miami",
    price: 950000,
    type: "Villa",
    status: "sale",
    bedrooms: 6,
    bathrooms: 5,
    area: 5200,
    features: true,
    image: "/images/image4.jpg",
    description:
      "Luxury beachfront villa with private pool, ocean views, and premium amenities.",
  },
  {
    id: "5",
    title: "Suburban Townhouse",
    location: "Dallas",
    price: 2800,
    type: "Townhouse",
    status: "rent",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    features: true,
    image: "/images/image5.jpg",
    description:
      "Modern townhouse in a quiet neighborhood with easy access to schools and shopping.",
  },
  {
    id: "6",
    title: "Mountain View Cabin",
    location: "Denver",
    price: 320000,
    type: "Cabin",
    status: "sale",
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    features: false,
    image: "/images/image6.jpg",
    description:
      "Charming cabin surrounded by nature with breathtaking mountain views.",
  },
  {
    id: "7",
    title: "Executive Penthouse",
    location: "San Francisco",
    price: 6500,
    type: "Penthouse",
    status: "rent",
    bedrooms: 4,
    bathrooms: 4,
    area: 3000,
    features: true,
    image: "/images/image7.jpg",
    description:
      "Exclusive penthouse featuring panoramic city views and luxurious interiors.",
  },
  {
    id: "8",
    title: "Country Side Farmhouse",
    location: "Nashville",
    price: 540000,
    type: "Farmhouse",
    status: "sale",
    bedrooms: 4,
    bathrooms: 3,
    area: 4000,
    features: true,
    image: "/images/image8.jpg",
    description:
      "Spacious farmhouse with large land area, barns, and a peaceful environment.",
  },
  {
    id: "9",
    title: "Urban Loft",
    location: "Seattle",
    price: 2200,
    type: "Loft",
    status: "rent",
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    features: false,
    image: "/images/image9.jpg",
    description:
      "Trendy loft with open-concept design, high ceilings, and modern finishes.",
  },
  {
    id: "10",
    title: "Luxury Mansion",
    location: "Houston",
    price: 1800000,
    type: "Mansion",
    status: "sale",
    bedrooms: 8,
    bathrooms: 7,
    area: 8500,
    features: true,
    image: "/images/image10.jpg",
    description:
      "Magnificent mansion offering premium architecture, landscaped gardens, and private amenities.",
  },
];
